# How frequently would you like UUIDs to be updated?
# Formatting: s m h d w mo y -> 30s = 30 seconds; 12m = 12 minutes; 5w = 5 weeks;
#                            1y3mo3d12m = 1 year 3 months 3 days 12 minutes.
# Default: 7d (7 days)
UUID_Refresh_Frequency: 7d

# How long of a cooldown would you like between API attempts after an attempt fails?
# Applies to each individual UUID or User name.
# Formatting: s m h d w mo y -> 30s = 30 seconds; 12m = 12 minutes; 5w = 5 weeks;
#                            1y3mo3d12m = 1 year 3 months 3 days 12 minutes.
# Default: 1m (1 minute)
API_Failure_Cooldown: 1m