# How frequently would you like UUIDs to be updated?
# Formatting: s m h d w y -> 30s = 30 seconds; 12m = 12 minutes; 5w = 5 weeks;
#                            1y3d12m = 1 year 3 days 12 minutes.
# Default: 7d (7 days)
UUID_Refresh_Frequency: 7d