name: mcuuid
main: com.thekdub.mcuuid.MCUUID
version: 1.1.1
author: thekdub
website: http://unknowntekkit.com
commands:
  mcuuid:
    description: Retrieve a user's UUID or name using their name or UUID respectively.
    aliases: [finduuid,minecraftuuid]
    permission: mcuuid.search
    usage: /MCUUID (Name / UUID / .reload) [.history] [.update]